### ISSUE TITLE
Error at Programming Interface

### ISSUE THREAD

**Issue by Batur123** [rodion-arr/google-index#27]
![Yeni Bit Eşlem Resmi](https://user-images.githubusercontent.com/32031460/145203580-5f44124a-b579-4a77-8fbd-80cf62a90754.jpg)
![image](https://user-images.githubusercontent.com/32031460/145203854-3f13dc2a-b26e-41cc-9ea3-ffd5c20d06ae.png)
![image](https://user-images.githubusercontent.com/32031460/145203881-a91b05b0-fafa-4c3e-b1c9-422ee5d751d3.png)

OS Centos 7
Node 14.17.2
NPM 7.19.1

Additional;
![image](https://user-images.githubusercontent.com/32031460/145204356-c3b2a84a-6091-48b1-a07f-26260557ac60.png)

**Comment by rodion-arr** [comment]
The lib uses `puppeteer` under the hood, so I assume you need to setup it's dependencies on the machine.
Probably this will help - https://frugalisminds.com/how-to-setup-puppeteer-in-centos-7/

**Comment by Batur123** [comment]
> The lib uses `puppeteer` under the hood, so I assume you need to setup its dependencies on the machine. Probably this will help - https://frugalisminds.com/how-to-setup-puppeteer-in-centos-7/

I did all the instructions on that webpage. Didn't work either. It still gives the same error.

**Comment by rodion-arr** [comment]
I can suggest you to try run `count` function with `true` as second argument:

```javascript
await count(data[1], true);
```

This fill run `puppeteer` with `--no-sandbox` flag

**Comment by rodion-arr** [comment]
I'm closing this issue as I believe it is related to missing `puppeteer` dependencies, not directly related to the package
